"""Administration : types et chambres, menu, utilisateurs (création, mot de passe, désactivation), restrictions du profil IT."""
import re
from playwright.sync_api import expect
from common import BASE, launch, login_mfa, scenario, shot, submit_credentials

with scenario() as p:
    b = launch(p)
    ctx = b.new_context(viewport={'width': 1440, 'height': 1000})
    page = ctx.new_page()
    login_mfa(page, 'admin@hotel.local')
    nav = page.get_by_role('navigation')
    for label in ['Chambres', 'Menu', 'Utilisateurs']:
        expect(nav.get_by_role('link', name=label, exact=True)).to_be_visible()
    print('0. menu Administration : 3 entrées OK')

    # 1. Chambres : nouveau type, nouvelle chambre, modification
    page.goto(BASE + '/admin/rooms')
    page.get_by_role('button', name='Nouveau type').click()
    page.get_by_label('Code').fill('ste')
    page.get_by_label('Nom', exact=True).fill('Suite')
    page.get_by_label('Capacité').fill('3')
    page.get_by_label('Tarif de base / nuit').fill('210,50')
    page.get_by_role('button', name='Enregistrer').click()
    ste = page.locator('section:has(#types-title) tr', has=page.locator('td', has_text=re.compile(r'^STE$')))
    expect(ste).to_contain_text('210,50')
    page.get_by_role('button', name='Nouvelle chambre').click()
    page.get_by_label('Numéro').fill('401')
    page.get_by_label('Étage').fill('4')
    page.locator('main form select').select_option(label='STE – Suite')
    page.get_by_role('button', name='Enregistrer').click()
    r401 = page.locator('section:has(#rooms-title) tr', has=page.locator('td', has_text=re.compile(r'^401$')))
    expect(r401).to_contain_text('STE')
    expect(ste).to_contain_text('1')
    page.get_by_role('button', name='Modifier 401').click()
    page.get_by_label('Numéro').fill('402')
    page.get_by_role('button', name='Enregistrer').click()
    expect(page.locator('td', has_text=re.compile(r'^402$'))).to_be_visible()
    # Doublon de code : erreur de l'API affichée
    page.get_by_role('button', name='Nouveau type').click()
    page.get_by_label('Code').fill('DBL'); page.get_by_label('Nom', exact=True).fill('X')
    page.get_by_label('Capacité').fill('2'); page.get_by_label('Tarif de base / nuit').fill('10')
    page.get_by_role('button', name='Enregistrer').click()
    expect(page.locator('main [role=alert]').first).to_be_visible()
    page.get_by_role('button', name='Annuler').click()
    shot(page, 'admin_rooms', full_page=True)
    print('1. chambres et types OK')

    # 2. Menu : nouvelle entrée visible dans la navigation, masquage, suppression
    page.goto(BASE + '/admin/menu')
    page.get_by_role('button', name='Nouvelle entrée').click()
    page.get_by_label('Clé').fill('help')
    page.get_by_label('Lien').fill('/help')
    page.get_by_label('Libellé (français)').fill('Aide')
    page.get_by_label('Libellé (anglais)').fill('Help')
    page.get_by_label('Libellé (arabe)').fill('مساعدة')
    page.get_by_role('button', name='Enregistrer').click()
    expect(nav.get_by_role('link', name='Aide')).to_be_visible()
    page.get_by_role('button', name='Masquer : Aide').click()
    expect(nav.get_by_role('link', name='Aide')).to_have_count(0)
    page.get_by_role('button', name='Modifier : Aide').click()
    page.get_by_label('Libellé (français)').fill('Aide en ligne')
    page.get_by_role('button', name='Enregistrer').click()
    expect(page.locator('main')).to_contain_text('Aide en ligne')
    shot(page, 'admin_menu', full_page=True)
    page.get_by_role('button', name='Supprimer : Aide en ligne').click()
    page.get_by_role('dialog').get_by_role('button', name='Supprimer').click()
    expect(page.locator('main')).not_to_contain_text('Aide en ligne')
    print('2. menu : création, masquage, modification, suppression OK')

    # 3. Utilisateurs : création, connexion, nouveau mot de passe, désactivation
    page.goto(BASE + '/admin/users')
    page.get_by_role('button', name='Nouvel utilisateur').click()
    dlg = page.get_by_role('dialog')
    dlg.get_by_label('Nom complet').fill('Nadia Haddad')
    dlg.get_by_label('Email').fill('nadia@hotel.local')
    dlg.get_by_label('Mot de passe initial').fill('court')
    dlg.get_by_role('button', name='Créer le compte').click()
    expect(dlg).to_be_visible()  # validation native : 12 caractères minimum
    dlg.get_by_label('Mot de passe initial').fill('Une phrase de passe')
    dlg.get_by_role('button', name='Créer le compte').click()
    expect(page.get_by_role('status')).to_contain_text('Compte de Nadia Haddad créé.')
    nadia = page.locator('tr', has_text='nadia@hotel.local')
    expect(nadia).to_contain_text('Réception')
    page.get_by_role('button', name='Nouveau mot de passe : Nadia Haddad').click()
    dlg.get_by_label('Nouveau mot de passe').fill('Nouvelle phrase secrète')
    dlg.get_by_role('button', name='Confirmer').click()
    expect(page.get_by_role('status')).to_contain_text('Mot de passe de Nadia Haddad remplacé.')
    nadia.get_by_role('button', name='Désactiver').click()
    dlg.get_by_role('button', name='Confirmer').click()
    expect(nadia).to_contain_text('Désactivé')
    me_row = page.locator('tr', has_text='admin@hotel.local')
    expect(me_row.get_by_role('button', name='Désactiver')).to_have_count(0)
    shot(page, 'admin_users', full_page=True)
    ctx2 = b.new_context(); p2 = ctx2.new_page()
    submit_credentials(p2, 'nadia@hotel.local', 'Nouvelle phrase secrète')
    expect(p2.locator('[role=alert]').first).to_be_visible()
    ctx2.close()
    nadia.get_by_role('button', name='Réactiver').click()
    expect(nadia).to_contain_text('Actif')
    ctx2 = b.new_context(); p2 = ctx2.new_page()
    submit_credentials(p2, 'nadia@hotel.local', 'Nouvelle phrase secrète')
    p2.wait_for_url(BASE + '/')
    ctx2.close()
    print('3. utilisateurs : création, mot de passe, désactivation, réactivation OK')
    ctx.close()

    # 4. Profil IT : pas d'action sur les comptes Direction, rôle Direction absent des choix
    ctx = b.new_context(viewport={'width': 1440, 'height': 1000})
    page = ctx.new_page()
    login_mfa(page, 'it@hotel.local')
    page.goto(BASE + '/admin/users')
    admin_row = page.locator('tr', has_text='admin@hotel.local')
    expect(admin_row.get_by_role('button')).to_have_count(0)
    page.get_by_role('button', name='Nouvel utilisateur').click()
    options = page.get_by_role('dialog').locator('select').first.locator('option').all_inner_texts()
    assert 'Direction' not in options, options
    print('4. profil IT restreint OK')
    b.close()
